services:
  postgres:
    image: postgres:17
    container_name: fhir-lint-postgres
    environment:
      POSTGRES_DB: fhirlint
      POSTGRES_USER: fhirlint
      POSTGRES_PASSWORD: fhirlint
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
